services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver_container
    ports:
      - "1433:1433" # Mapea el puerto SQL Server al host
    environment:
      ACCEPT_EULA: "Y"            # Acepta la licencia de SQL Server
      SA_PASSWORD: "TuPassword123" # Establece la contraseña del usuario "sa"
    volumes:
      - sql_data:/var/opt/mssql # Almacena los datos en un volumen persistente
    restart: always              # Reinicia automáticamente el contenedor si falla

volumes:
  sql_data:
    # driver: local
    external: false